### ISSUE TITLE
error when running x.py in frame dir

### ISSUE THREAD

**Issue by randliu** [randliu/patrol#1]
Traceback (most recent call last):
  File "x.py", line 114, in <module>
    lst_xml_url=get_lst_xml_url()
  File "x.py", line 40, in get_lst_xml_url
    l_pkg_dir_name = os.listdir(pkgs_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rand/Code/PycharmProjects/patrol/frame/packages/'

**Comment by randliu** [comment]
os.path.realpath(__file__)
